development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:811e3e107c31f0f171c93d4eac8e73ec@hammerjaw.redistogo.com:10091/ #<%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: onebitinder_api_production
